// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vnkwsmbrfdtqrnacdthw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZua3dzbWJyZmR0cXJuYWNkdGh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNjUxMDYsImV4cCI6MjA2MDY0MTEwNn0.eHzUqQGR8gb1I3sJxjVcx7hhbAfBHlqYyRNWreJ12gQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);